# Generated by Django 4.2.1 on 2023-06-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Explication', models.CharField(max_length=200)),
                ('Justifie_bool', models.BooleanField()),
                ('Justif_url', models.CharField(blank=True, max_length=200, null=True)),
                ('Commentaire_enseignant', models.CharField(blank=True, max_length=100, null=True)),
                ('Inspection_terminee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inspection_finie', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_cours', models.CharField(max_length=50)),
                ('Date', models.DateField(max_length=50)),
                ('Duree', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('boursier', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupeEtu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
    ]
