# Generated by Django 2.1.15 on 2023-06-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABSENCES', '0002_auto_20230610_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='absences',
            name='Checke_par',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ABSENCES.Enseignant'),
        ),
        migrations.AddField(
            model_name='absences',
            name='Cours',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ABSENCES.Cours'),
        ),
        migrations.AddField(
            model_name='absences',
            name='Etudiant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ABSENCES.Etudiants'),
        ),
        migrations.AddField(
            model_name='archives',
            name='Commentaire_enseignant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commentaire_enseignant_archives', to='ABSENCES.Absences'),
        ),
        migrations.AddField(
            model_name='archives',
            name='Cours',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ABSENCES.Cours'),
        ),
        migrations.AddField(
            model_name='archives',
            name='Etudiant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ABSENCES.Etudiants'),
        ),
        migrations.AddField(
            model_name='archives',
            name='Explication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='explication_archives', to='ABSENCES.Absences'),
        ),
        migrations.AddField(
            model_name='archives',
            name='Justificatif',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='justificatif_archives', to='ABSENCES.Absences'),
        ),
        migrations.AddField(
            model_name='archives',
            name='Justifie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='justifie_archives', to='ABSENCES.Absences'),
        ),
        migrations.AddField(
            model_name='archives',
            name='Justifie_par',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='justifie_par_archives', to='ABSENCES.Absences'),
        ),
        migrations.AddField(
            model_name='cours',
            name='Groupe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ABSENCES.GroupeEtu'),
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ABSENCES.Enseignant'),
        ),
        migrations.AddField(
            model_name='etudiants',
            name='groupe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ABSENCES.GroupeEtu'),
        ),
    ]
