# Generated by Django 2.1.15 on 2023-06-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSENCES', '0003_auto_20230611_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='Date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
