# Generated by Django 2.1.15 on 2023-06-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABSENCES', '0006_auto_20230612_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='Groupes',
        ),
        migrations.AddField(
            model_name='cours',
            name='Groupes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ABSENCES.GroupeEtu'),
        ),
    ]
