# Generated by Django 2.1.15 on 2023-06-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABSENCES', '0007_auto_20230613_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archives',
            name='Commentaire_enseignant',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='Cours',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='Etudiant',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='Explication',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='Justificatif',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='Justifie',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='Justifie_par',
        ),
        migrations.AlterField(
            model_name='absences',
            name='Checke_par',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ABSENCES.Enseignant'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ABSENCES.Enseignant'),
        ),
        migrations.DeleteModel(
            name='Archives',
        ),
    ]
