# Generated by Django 2.1.15 on 2023-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSENCES', '0008_auto_20230615_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absences',
            name='Justif_url',
            field=models.FileField(default='justifications/test.pdf', upload_to='justifications/'),
        ),
    ]
