# Generated by Django 2.1.15 on 2023-06-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSENCES', '0005_auto_20230611_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='Duree',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
